<?php

/**
 * @file
 * Install module hooks for Infomaniak OIDC module.
 */

/* @noinspection PhpUnnecessaryFullyQualifiedNameInspection */
/* @noinspection PhpUnusedParameterInspection */
/* @noinspection PhpUnused */

/**
 * Implements hook_uninstall().
 */
function infomaniak_connect_uninstall(): void {
  // Remove configuration.
  Drupal::configFactory()
    ->getEditable('openid_connect.client.infomaniak')
    ->delete();
}
